### PR TITLE
Delete CNAME

### PR DESCRIPTION
**Pull request by ghost**
This is only needed in the gh-pages branch

### CODE REVIEW

**Comment by gbaman** [comment]
CNAME file is kind of important, given that it tells the github pages system where to point traffic looking for the address to. It must be in master as master auto builds gp-pages, which is the github pages site. It is then copied to he gh-pages site where it is read by github for redirection.
So removing it would be a bad idea..

**Comment by ghost** [comment]
Oh ok, this is interesting. I'm trying to auto build gh-pages at miniputing/setups GitHub repository myself without success. Are you aware of any good documentation about it? :-)

**Comment by gbaman** [comment]
The reason for this is I have a server sitting with a hacked together script (based on [Grip](https://pypi.python.org/pypi/grip/)) that builds the site. It checks every 5 mins if there has been a change to the master branch. If so it pulls the documentation and builds the html version.
Is pretty hacked together and we are working right now on a more long term solution.

**Comment by ghost** [comment]
I see. I was hoping for a clean straight forward solution as I already spent more time than I wished figuring out that Jekyll thing. Too bad GitHub automatic generator isn't smart enough to process the whole thing. Thanks!

**Pull request closed without merging**
